OUTPUT_ARCH( "riscv" )
ENTRY( _main )


SECTIONS
{
 . = 0x0;
 
  .text : {
    *(.text .text.*)
  }

  .rodata : {
  . = ALIGN(16);
  *(.srodata .srodata.*)
  . = ALIGN(16);
  *(.rodata .rodata.*)
}

.eh_frame : {
  *(.eh_frame)
  *(.eh_frame.*)
}

. = ALIGN(0x1000);
.data : {
  . = ALIGN(16);
  *(.sdata .sdata.*)
  . = ALIGN(16);
  *(.data .data.*)
}

  .bss : {
    . = ALIGN(16);
    *(.sbss .sbss.*) /* do not need to distinguish this from .bss */
    . = ALIGN(16);
    *(.bss .bss.*)
  }


  PROVIDE(end = .);
}
